### ISSUE TITLE
Error: no release found with tag 0.1.0

### ISSUE THREAD

**Issue by bacongobbler** [rajatjindal/spin-plugin-releaser#18]
If you push a new tag called `v0.1.0` with this workflow:

```
    - name: Release Plugin
      uses: rajatjindal/spin-plugin-releaser@v1
      with:
        github_token: ${{ github.token }}
        upload_checksums: true
        template_file: contrib/spin-plugin.json.tmpl
```

You will receive this error:

```
> Run rajatjindal/spin-plugin-releaser@v1
Error: no release found with tag 0.1.0
```

Notice how it is looking for a tag with the name `0.1.0` - the `v` has been stripped from the tag name.
